script: |
  whoami
  hostname

  docker --version

  docker pull ${{ secrets.DOCKER_USERNAME }}/devops-cicd-pipeline:latest

  docker stop devops-app || true
  docker rm devops-app || true

  docker run -d \
    --name devops-app \
    --restart unless-stopped \
    -p 5000:80 \
    ${{ secrets.DOCKER_USERNAME }}/devops-cicd-pipeline:latest

  docker ps

  curl http://localhost:5000

  sudo systemctl restart nginx
